### ISSUE TITLE
install issue

### ISSUE THREAD

**Issue by krz** [bnpy/bnpy#1]
Hi,
I have some install problem. I use anaconda and ran into the following issue:

```
>>> import bnpy                                                                                                                                      
/home/.../bnpy/util/lib/sparseResp/libsparsemix.so: cannot open shared object file: No such file or directory                             
bnpy/util/lib/sparseResp/CPPLoader.py:40: UserWarning: /home/.../bnpy/util/lib/sparseResp/libsparsetopicsmanydocs.so: cannot open shared object file: No such file or directory
  warnings.warn(str(e))
```

I tried installing on two different machines, ubuntu 16.04 and kubuntu 16.10, both result in the same error. Installing does not produce and error but install checking leads to the same errors as above when loading the package. My anaconda install is up to date.

I also hope for python3 support in the future.

Thanks

**Comment by michaelchughes** [comment]
Thanks for your feedback!

Long story short, this is a warning message, not an error. Missing these files is NOT an issue if you just want to try out basic functionality. You should be able to try all examples in the [Example Gallery](http://bnpy.readthedocs.io/en/latest/examples/index.html) as is, without any reinstallation, even if you see this message.

By default, bnpy 0.1.4 would print this message if *.so files (compiled C++ libraries) needed for some advanced features (sparse representations of local responsibility parameters for variational algorithms) are not available. If you really want these features, you need to have the Eigen C++ matrix libraries properly installed on your system and visible to bnpy's install scripts via the EIGENPATH environment variable (see http://bnpy.readthedocs.io/en/latest/installation.html#advanced-installation).

To avoid folks thinking this is a problem in the future, I've updated master to version 0.1.5, which no longer prints any warning messages in general about .so files missing. Instead, usage of basic bnpy functions works as normal, and if users try to use functions which require the .so libraries but did not follow the advanced install instructions to properly compile things, an appropriate error message appears.

**Comment by michaelchughes** [comment]
Closing this issue, since I think it's resolved. If you have other problems, please do open a new issue!

FYI: Python 3 support is something I'm open to, but I don't have the cycles to work on for fore-seeable future. If anybody wants to take this on, I'd welcome it, but I'm not going to prioritize it myself.
