### ISSUE TITLE
How to get predicted label for each sample

### ISSUE THREAD

**Issue by Naghipourfar** [bnpy/bnpy#11]
Hi, I applied 'DPMM' Algorithm on my dataset and it has converged. However, I can't find the predicted labels for each sample in the dataset to do some analysis.

**Comment by michaelchughes** [comment]
Let's assume you have a dataset of interest named Data (a bnpy dataset object, what you'd pass into bnpy.run), and a trained model named model (a bnpy HModel object, this would be returned by any call to bnpy.run). Then, you can calculate local assignments (and other necessary parameters) via:

```
LP = model.calc_local_params(Data)
```

Here, LP is a dictionary object. It will always have a field called resp, which will hold the cluster membership probabilities for each data atom in the dataset in a 2D array that has N rows (one per data item) and K columns (one per learned cluster).

If you just wanted to get the hard assignment of each data item to its most likely cluster, you can do:
```
Z = LP['resp'].argmax(axis=1)
```
Here, Z is a 1D array of size N. Entry Z[n] will be an integer in the range {0, 1, 2, ... K-1}.

Hope that helps!
