### ISSUE TITLE
errors when I use birth merge shuffle moves

### ISSUE THREAD

**Issue by minnieyao** [bnpy/bnpy#19]
Dear author, 
I am trying to use birth merge shuffle on my own data. The command is as follows:
hmmdiag_trained_model, hmmdiag_info_dict = bnpy.run(
    myData, 'DPMixtureModel', 'Gauss', 'memoVB',
    output_path='/tmp/AsteriskK8/trymoves-K=25/',
    nLap=100, nTask=1, nBatch=1,
    sF=0.1, ECovMat='eye',
    K=25, initname='randexamples',
    moves='birth,merge,shuffle',
    m_startLap=5, b_startLap=2, b_Kfresh=4
    )
I got the following error 

SGE Grid Job ID: 17687402
Dataset Summary:
GroupXData
  total size: 2 units
  batch size: 2 units
  num. batches: 1
Allocation Model:  DP mixture with K=0. Concentration gamma0= 1.00
Obs. Data  Model:  Gaussian with full covariance.
Obs. Data  Prior:  Gauss-Wishart on mean and covar of each cluster
  E[  mean[k] ] = 
   [0. 0.]  ...
  E[ covar[k] ] = 
  [[0.1 0. ]
   [0.  0.1]] ...
Initialization:
  initname = randexamples
  K = 25 (number of clusters)
  seed = 1607680
  elapsed_time: 0.4 sec
Learn Alg: memoVB | task  1/1 | alg. seed: 1607680 | data order seed: 8541952
task_output_path: /tmp/AsteriskK8/trymoves-K=25/1
BIRTH @ lap 1.00: Disabled. Waiting for lap >= 2 (--b_startLap).
MERGE @ lap 1.00: Disabled. Cannot plan merge on first lap. Need valid SS that represent whole dataset.
    1.000/100 after      1 sec. |    809.7 MiB | K   25 | loss  1.794276458e-01 |  
MERGE @ lap 2.00: Disabled. Waiting for lap >= 5 (--m_startLap).
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-13-ee5edbef4798> in <module>()
     12     K=25, initname='randexamples',
     13     moves='birth,merge,shuffle',
---> 14     m_startLap=5, b_startLap=2, b_Kfresh=4
     15     )
     16 

/home/liji7c/Python_pakg/bnpy/bnpy/Run.pyc in run(dataName, allocModelName, obsModelName, algName, doSaveToDisk, doWriteStdOut, taskID, **kwargs)
     92             dataName, allocModelName,
     93             obsModelName, algName,
---> 94             doSaveToDisk, doWriteStdOut)
     95         if (taskid == starttaskid or info_dict['loss'] < best_loss):
     96             bestModel = hmodel

/home/liji7c/Python_pakg/bnpy/bnpy/Run.pyc in _run_task_internal(jobname, taskid, nTask, ReqArgs, KwArgs, UnkArgs, dataName, allocModelName, obsModelName, algName, doSaveToDisk, doWriteStdOut)
    221 
    222     # Fit the model to the data!
--> 223     RunInfo = learnAlg.fit(hmodel, Data)
    224     RunInfo['UnkArgs'] = UnkArgs
    225     RunInfo['KwArgs'] = KwArgs

/home/liji7c/Python_pakg/bnpy/bnpy/learnalg/MemoVBMovesAlg.pyc in fit(self, hmodel, DataIterator, **kwargs)
    118                 MovePlans=MovePlans,
    119                 MoveRecordsByUID=MoveRecordsByUID,
--> 120                 MoveLog=MoveLog)
    121 
    122             self.saveDebugStateAtBatch(

/home/liji7c/Python_pakg/bnpy/bnpy/learnalg/MemoVBMovesAlg.pyc in calcLocalParamsAndSummarize_withExpansionMoves(self, DataIterator, curModel, SS, batchID, lapFrac, MovePlans, MoveRecordsByUID, MoveLog, **kwargs)
    371                     nBatch=self.nBatch,
    372                     batchPos=batchPos,
--> 373                     **self.algParams['birth'])
    374             ElapsedTimeLogger.stopEvent('birth', 'localexpansion')
    375 

/home/liji7c/Python_pakg/bnpy/bnpy/birthmove/BCreateManyProposals.pyc in makeSummariesForManyBirthProposals(Dslice, curModel, curLPslice, curSSwhole, curSSslice, LPkwargs, newUIDs, b_targetUIDs, xSSProposalsByUID, MovePlans, MoveRecordsByUID, taskoutpath, lapFrac, batchID, batchPos, nBatch, **BArgs)
     66             lapFrac=lapFrac,
     67             batchID=batchID,
---> 68             **BArgs)
     69         if xSSslice is not None:
     70             # Proposal successful, with at least 2 non-empty clusters.

/home/liji7c/Python_pakg/bnpy/bnpy/birthmove/BCreateOneProposal.pyc in makeSummaryForBirthProposal_HTMLWrapper(Dslice, curModel, curLPslice, **kwargs)
     70     else:
     71         xSSslice, DebugInfo = makeSummaryForBirthProposal(
---> 72             Dslice, curModel, curLPslice, **kwargs)
     73 
     74     # Write output to HTML

/home/liji7c/Python_pakg/bnpy/bnpy/birthmove/BCreateOneProposal.pyc in makeSummaryForBirthProposal(Dslice, curModel, curLPslice, curSSwhole, b_creationProposalName, targetUID, ktarget, newUIDs, LPkwargs, lapFrac, batchID, seed, b_nRefineSteps, b_debugOutputDir, b_minNumAtomsForNewComp, b_doInitCompleteLP, b_cleanupWithMerge, b_method_initCoordAscent, vocabList, **kwargs)
    162         logFunc=BLogger.pprint,
    163         NiterForBregmanKMeans=kwargs['b_NiterForBregmanKMeans'],
--> 164         **kwargs)
    165     # EXIT EARLY: if proposal initialization fails (not enough data).
    166     if xInitSStarget is None:

/home/liji7c/Python_pakg/bnpy/bnpy/init/FromScratchBregman.pyc in initSS_BregmanDiv(Dslice, curModel, curLPslice, K, ktarget, seed, includeAllocSummary, NiterForBregmanKMeans, logFunc, **kwargs)
    134             ktarget,
    135             K=K,
--> 136             **kwargs)
    137     if logFunc:
    138         logFunc(DebugInfo['targetAssemblyMsg'])

/home/liji7c/Python_pakg/bnpy/bnpy/init/FromScratchBregman.pyc in makeDataSubsetByThresholdResp(Data, curModel, curLP, ktarget, K, minRespForEachTargetAtom, **kwargs)
    484                 )
    485             return DebugInfo, None, None, None, None
--> 486         targetData = Data.make_subset(example_id_list=chosenRespIDs)
    487         targetX = targetData.X
    488         if curLP is None:

TypeError: make_subset() got an unexpected keyword argument 'example_id_list'

Do you know potential problems?

Thank you

**Comment by minnieyao** [comment]
I have solve this problem. Thank you!

**Comment by michaelchughes** [comment]
Great! Can you perhaps say a little bit about what you needed to do to fix it? Just in case others find this issue when searching for errors of their own?

**Comment by minnieyao** [comment]
The problem is the total size of data is too small. If the size is increased, say 6 groups, there will be no error any more. By the  way, where I can find  more instructions of parameters of moves,except for your examples?
