### ISSUE TITLE
Question: How to use online methods

### ISSUE THREAD

**Issue by Jamesadamar** [bnpy/bnpy#5]
First of all, really great job! I skimmed through the provided examples and so far I was only able to find examples which seem to run the algorithm from scratch. At least that's how I understand the bnpy.run method. Maybe there is a parameter for this method I haven't seen yet. We need for our project a DP-GMM online method, so the combination DPMixtureModel  + Gauss + soVB seems to be the perfect combination. But I am not sure how to run the algorithm with online data, that is providing new data to the already trained model, or do you pass the learned model as a parameter to the run method? Maybe you could provide me a few hints to get started with your code, your help is very much appreciated.

**Comment by Jamesadamar** [comment]
In the docs I've found that there should be a method ContinueRun.py which would exactly do the required task, but it seems that this method is not implemented yed, right?

**Comment by michaelchughes** [comment]
Thanks for your interest and sorry for the delay! Response below, please do comment back here with any further questions.

I've added a new example script that provides an example of providing new data to an already trained model (as a special instance of generally "warm starting" given a pre-trained model)

See the raw script .py file here (the docs on bnpy.readthedocs.io should update accordingly soon):
https://github.com/bnpy/bnpy/blob/master/examples/01_asterisk_K8/plot-04-demo%3Dvb_warm_start_from_existing_model-model%3Ddp_mix%2Bgauss.py

This script provides some examples of taking a pretrained model, and applying it to an expanded dataset (containing the old examples and some new examples). 

I will emphasize one point about terminology. For many applications, **online** processing means that the dataset keeps growing.  Unfortunately, the "stochastic variational inference" method does not quite satisfy this definition. Its update rules require knowing the fixed total size of the full dataset in advance (this number is needed at every update). So it is better described as a "scalable" or "minibatch" algorithm, rather than a truly "online" or "streaming" algorithms.

That said, given new data, you can always take the latest complete dataset as your "fixed dataset", and apply stochastic VB (soVB) or memoized VB (memoVB) accordingly using a warm start from a previous training run. So perhaps this distinction isn't a show-stopper in practice.

**Comment by Jamesadamar** [comment]
Thank you for your nice reply. Your current example throws the following Exception:
```Python
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-21-a93526038695> in <module>()
      9     initLP=full_trained_model.calc_local_params(dataset),
     10     initname=full_info_dict['task_output_path'],
---> 11     **dict(delete_kwargs.items() + merge_kwargs.items()))

/home/michael/work/git/bnpy/bnpy/Run.pyc in run(dataName, allocModelName, obsModelName, algName, doSaveToDisk, doWriteStdOut, taskID, **kwargs)
     92             dataName, allocModelName,
     93             obsModelName, algName,
---> 94             doSaveToDisk, doWriteStdOut)
     95         if (taskid == starttaskid or info_dict['loss'] < best_loss):
     96             bestModel = hmodel

/home/michael/work/git/bnpy/bnpy/Run.pyc in _run_task_internal(jobname, taskid, nTask, ReqArgs, KwArgs, UnkArgs, dataName, allocModelName, obsModelName, algName, doSaveToDisk, doWriteStdOut)
    187         algName=ReqArgs['algName'],
    188         KwArgs=KwArgs,
--> 189         verbose=(taskid == 1 or jobID > 0),
    190         )
    191 

/home/michael/work/git/bnpy/bnpy/Run.pyc in make_initialized_model(Data, allocModelName, obsModelName, algName, allocPriorArgsDict, obsPriorArgsDict, initArgsDict, taskid, seed, verbose, KwArgs)
    392         Log.info("  seed = %d" % seed)
    393         start_time_sec = time.time()
--> 394     hmodel.init_global_params(Data, seed=seed, taskid=taskid, **initArgsDict)
    395     if verbose:
    396         Log.info("  elapsed_time: %.1f sec" % (time.time() - start_time_sec))

/home/michael/work/git/bnpy/bnpy/HModel.pyc in init_global_params(self, Data, **initArgs)
    188 
    189         if initname.count(os.path.sep) > 0:
--> 190             init.FromSaved.init_global_params(self, Data, **initArgs)
    191         elif initname.count('true') > 0:
    192             init.FromTruth.init_global_params(self, Data, **initArgs)

/home/michael/work/git/bnpy/bnpy/init/FromSaved.pyc in init_global_params(hmodel, Data, initname, **kwargs)
     41             initname2 = os.path.join(initname, str(kwargs['taskid']))
     42             init_global_params_from_bnpy_format(
---> 43                 hmodel, Data, initname2, **kwargs)
     44     elif initname.count('.mat') > 0:
     45         # Handle external external formats (not bnpy models) saved as MAT file

/home/michael/work/git/bnpy/bnpy/init/FromSaved.pyc in init_global_params_from_bnpy_format(hmodel, Data, initname, initLapFrac, prefix, **kwargs)
     63         storedModel, lap = ModelReader.loadModelForLap(initname, initLapFrac)
     64     else:
---> 65         storedModel = ModelReader.load_model(initname, prefix)
     66     try:
     67         hmodel.set_global_params(hmodel=storedModel,

AttributeError: 'module' object has no attribute 'load_model'```

**Comment by michaelchughes** [comment]
Thanks! I forgot to mention that I had made that change (renaming to load_model_at_lap) under the hood and uploaded the latest versions to github. 

Now, I've fixed things everywhere (even on PyPI). If you build the latest version from github or via "pip install bnpy", you should not have this error.

Thanks again for following up. I'll go ahead and consider this closed.

**Comment by liuziyang365** [comment]
In the plot-04-demo=vb_warm_start_from_existing_model-model=dp_mix+gauss.ipynb
###
NotImplementedError                       Traceback (most recent call last)
<ipython-input-8-2a87ef2b5c2c> in <module>()
      4     nLap=100,
      5     sF=0.1, ECovMat='eye',
----> 6     initname=cold_info_dict['task_output_path'])

G:\document2\增量高斯混合\bnpy-master\bnpy\Run.pyc in run(dataName, allocModelName, obsModelName, algName, doSaveToDisk, doWriteStdOut, taskID, **kwargs)
     92             dataName, allocModelName,
     93             obsModelName, algName,
---> 94             doSaveToDisk, doWriteStdOut)
     95         if (taskid == starttaskid or info_dict['loss'] < best_loss):
     96             bestModel = hmodel

G:\document2\增量高斯混合\bnpy-master\bnpy\Run.pyc in _run_task_internal(jobname, taskid, nTask, ReqArgs, KwArgs, UnkArgs, dataName, allocModelName, obsModelName, algName, doSaveToDisk, doWriteStdOut)
    187         algName=ReqArgs['algName'],
    188         KwArgs=KwArgs,
--> 189         verbose=(taskid == 1 or jobID > 0),
    190         )
    191 

G:\document2\增量高斯混合\bnpy-master\bnpy\Run.pyc in make_initialized_model(Data, allocModelName, obsModelName, algName, allocPriorArgsDict, obsPriorArgsDict, initArgsDict, taskid, seed, verbose, KwArgs)
    392         Log.info("  seed = %d" % seed)
    393         start_time_sec = time.time()
--> 394     hmodel.init_global_params(Data, seed=seed, taskid=taskid, **initArgsDict)
    395     if verbose:
    396         Log.info("  elapsed_time: %.1f sec" % (time.time() - start_time_sec))

G:\document2\增量高斯混合\bnpy-master\bnpy\HModel.pyc in init_global_params(self, Data, **initArgs)
    205             if str(type(self.obsModel)).count('Gauss') > 0:
    206                 init.FromScratchGauss.init_global_params(self.obsModel,
--> 207                                                          Data, **initArgs)
    208             elif str(type(self.obsModel)).count('Mult') > 0:
    209                 init.FromScratchMult.init_global_params(self.obsModel,

G:\document2\增量高斯混合\bnpy-master\bnpy\init\FromScratchGauss.pyc in init_global_params(obsModel, Data, K, seed, initname, initBlockLen, **kwargs)
    112 
    113     else:
--> 114         raise NotImplementedError('Unrecognized initname ' + initname)
    115 
    116     tempLP = dict(resp=resp)

NotImplementedError: Unrecognized initname /tmp/AsteriskK8/coldstart-K=10/1
###
