### ISSUE TITLE
Broadcast Error with Moves - HDP-HMM Diag Gaussian model

### ISSUE THREAD

**Issue by vibhaanand** [bnpy/bnpy#6]
So I set up the model with the moves. I used the following settings for proposals (also from the old faithful example)

merge_kwargs = dict(
    m_startLap=10,
    m_pair_ranking_procedure='total_size',
    m_pair_ranking_direction='descending',
    )

delete_kwargs = dict(
    d_startLap=20,
    d_nRefineSteps=50,
    )

As expected, the code tries to create merges at lap 10 - but runs into issues - please see below.
WARNING: Found unrecognized keyword args. These are ignored.
  --alpha
Dataset Summary:
GroupXData
  total size: 6 units
  batch size: 6 units
  num. batches: 1
Allocation Model:  None
Obs. Data  Model:  Gaussian with diagonal covariance.
Obs. Data  Prior:  independent Gauss-Wishart prior on each dimension
  Wishart params
    nu = 14  ...
  beta = [ 12  12]  ...
  Expectations
  E[  mean[k]] =
  [ 0  0] ...
  E[ covar[k]] =
  [[ 1.  0.]
   [ 0.  1.]] ...
Initialization:
  initname = randexamples
  K = 20 (number of clusters)
  seed = 1607680
  elapsed_time: 0.0 sec
Learn Alg: memoVB | task  1/1 | alg. seed: 1607680 | data order seed: 8541952
task_output_path: /tmp/mocap6/showcase-K=20-model=HDPHMM+DiagGauss-ECovMat=1-eye/1
MERGE @ lap 1.00: Disabled. Cannot plan merge on first lap. Need valid SS that represent whole dataset.
DELETE @ lap 1.00: Disabled. Cannot delete before first complete lap, because SS that represents whole dataset is required.
    1.000/50 after      0 sec. |    132.0 MiB | K   20 | loss  3.716756017e+00 |  
MERGE @ lap 2.00: Disabled. Waiting for lap >= 10 (--m_startLap).
DELETE @ lap 2.00: Disabled. Waiting for lap >= 20 (--d_startLap).
    2.000/50 after      0 sec. |    132.6 MiB | K   20 | loss  3.611824567e+00 | Ndiff   30.418
MERGE @ lap 3.00: Disabled. Waiting for lap >= 10 (--m_startLap).
DELETE @ lap 3.00: Disabled. Waiting for lap >= 20 (--d_startLap).
    3.000/50 after      1 sec. |    132.8 MiB | K   20 | loss  3.579928854e+00 | Ndiff   18.080
MERGE @ lap 4.00: Disabled. Waiting for lap >= 10 (--m_startLap).
DELETE @ lap 4.00: Disabled. Waiting for lap >= 20 (--d_startLap).
    4.000/50 after      1 sec. |    132.8 MiB | K   20 | loss  3.565367190e+00 | Ndiff   19.077
MERGE @ lap 5.00: Disabled. Waiting for lap >= 10 (--m_startLap).
DELETE @ lap 5.00: Disabled. Waiting for lap >= 20 (--d_startLap).
    5.000/50 after      1 sec. |    132.8 MiB | K   20 | loss  3.552412231e+00 | Ndiff   18.396
MERGE @ lap 6.00: Disabled. Waiting for lap >= 10 (--m_startLap).
DELETE @ lap 6.00: Disabled. Waiting for lap >= 20 (--d_startLap).
    6.000/50 after      1 sec. |    132.8 MiB | K   20 | loss  3.547245682e+00 | Ndiff    9.353
MERGE @ lap 7.00: Disabled. Waiting for lap >= 10 (--m_startLap).
DELETE @ lap 7.00: Disabled. Waiting for lap >= 20 (--d_startLap).
    7.000/50 after      1 sec. |    132.8 MiB | K   20 | loss  3.545361199e+00 | Ndiff    3.043
MERGE @ lap 8.00: Disabled. Waiting for lap >= 10 (--m_startLap).
DELETE @ lap 8.00: Disabled. Waiting for lap >= 20 (--d_startLap).
    8.000/50 after      1 sec. |    132.8 MiB | K   20 | loss  3.542436507e+00 | Ndiff    8.684
MERGE @ lap 9.00: Disabled. Waiting for lap >= 10 (--m_startLap).
DELETE @ lap 9.00: Disabled. Waiting for lap >= 20 (--d_startLap).
    9.000/50 after      2 sec. |    132.8 MiB | K   20 | loss  3.533845903e+00 | Ndiff    8.233
DELETE @ lap 10.00: Disabled. Waiting for lap >= 20 (--d_startLap).
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-10-ac4e00e763d0> in <module>()
      5     alpha=alpha, gamma=gamma, sF=sF, ECovMat='eye',
      6     K=K, initname='randexamples',moves='merge,delete,shuffle',
----> 7     **dict(delete_kwargs.items() + merge_kwargs.items()))

c:\users\ibm_admin\documents\github\bnpy\bnpy\Run.pyc in run(dataName, allocModelName, obsModelName, algName, doSaveToDisk, doWriteStdOut, taskID, **kwargs)
     92             dataName, allocModelName,
     93             obsModelName, algName,
---> 94             doSaveToDisk, doWriteStdOut)
     95         if (taskid == starttaskid or info_dict['loss'] < best_loss):
     96             bestModel = hmodel

c:\users\ibm_admin\documents\github\bnpy\bnpy\Run.pyc in _run_task_internal(jobname, taskid, nTask, ReqArgs, KwArgs, UnkArgs, dataName, allocModelName, obsModelName, algName, doSaveToDisk, doWriteStdOut)
    221 
    222     # Fit the model to the data!
--> 223     RunInfo = learnAlg.fit(hmodel, Data)
    224     RunInfo['UnkArgs'] = UnkArgs
    225     RunInfo['KwArgs'] = KwArgs

c:\users\ibm_admin\documents\github\bnpy\bnpy\learnalg\MemoVBMovesAlg.pyc in fit(self, hmodel, DataIterator, **kwargs)
    168                             MoveLog=MoveLog,
    169                             MoveRecordsByUID=MoveRecordsByUID,
--> 170                             lapFrac=lapFrac,)
    171                 # Afterwards, always discard any tracked merge terms
    172                 SS.removeMergeTerms()

c:\users\ibm_admin\documents\github\bnpy\bnpy\learnalg\MemoVBMovesAlg.pyc in runMoves_Merge(self, hmodel, SS, loss, MovePlans, MoveLog, MoveRecordsByUID, lapFrac, **kwargs)
   1220             MoveRecordsByUID[pairTuple]['m_latestMinCount'] = minPairCount
   1221             propSS = SS.copy()
-> 1222             propSS.mergeComps(uidA=uidA, uidB=uidB)
   1223             propModel = hmodel.copy()
   1224             propModel.update_global_params(propSS)

c:\users\ibm_admin\documents\github\bnpy\bnpy\suffstats\SuffStatBag.pyc in mergeComps(self, kA, kB, uidA, uidB, fieldsToIgnore, **kwargs)
    379         self._mergeFieldsAtIndexKA(kA, kB, rowID, fieldsToIgnore)
    380         # Fill entry [kA] of each elboterm with correct value.
--> 381         self._mergeELBOTermsAtIndexKA(kA, kB, rowID)
    382 
    383         self._setMergeTermsAtIndexKAToNaN(kA, kB, rowID)

c:\users\ibm_admin\documents\github\bnpy\bnpy\suffstats\SuffStatBag.pyc in _mergeELBOTermsAtIndexKA(self, kA, kB, rowID)
    493                     if mArr.ndim == 3 and mArr.shape[1] == 2:
    494                         arr[kA, :] = mArr[rowID, 0]
--> 495                         arr[:, kA] = mArr[rowID, 1]
    496                     elif mArr.ndim <= 1:
    497                         arr[kA] = mArr[rowID]

ValueError: shape mismatch: value array of shape (20,) could not be broadcast to indexing result of shape (1,20)

**Comment by michaelchughes** [comment]
Thanks for reporting! I am able to reproduce this bug. I'll work later today on a quick fix... hopefully will have an easy answer within ~1 day or so.

**Comment by michaelchughes** [comment]
FIXED. Required some edits to sourcecode (basically, some return value in SuffStatBag.py was a 1D array of int instead of an int, so when used to slice an array the broadcasting was broken). Better version has been uploaded to github's master branch. I'll push the same fixes to PyPI soon.

I've created a new example in the gallery to show more directly how merges work for HDP-HMM, including some more advanced explanations of keyword arguments that control which merge proposals are attempted:
http://bnpy.readthedocs.io/en/latest/examples/08_mocap6/plot-02-demo=merge_moves_for_hdphmm.html

Thanks again for the bug report!
